using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

namespace Microsoft.Web.WebView2.Core.Raw;

[CompilerGenerated]
[TypeIdentifier("26D34152-879F-4065-BEA2-3DAA2CFADFB8", "Microsoft.Web.WebView2.Core.Raw.COREWEBVIEW2_PREFERRED_COLOR_SCHEME")]
public enum COREWEBVIEW2_PREFERRED_COLOR_SCHEME
{
	COREWEBVIEW2_PREFERRED_COLOR_SCHEME_AUTO,
	COREWEBVIEW2_PREFERRED_COLOR_SCHEME_LIGHT,
	COREWEBVIEW2_PREFERRED_COLOR_SCHEME_DARK
}
