using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

namespace Microsoft.Web.WebView2.Core.Raw;

[CompilerGenerated]
[TypeIdentifier("26D34152-879F-4065-BEA2-3DAA2CFADFB8", "Microsoft.Web.WebView2.Core.Raw.COREWEBVIEW2_TRACKING_PREVENTION_LEVEL")]
public enum COREWEBVIEW2_TRACKING_PREVENTION_LEVEL
{
	COREWEBVIEW2_TRACKING_PREVENTION_LEVEL_NONE,
	COREWEBVIEW2_TRACKING_PREVENTION_LEVEL_BASIC,
	COREWEBVIEW2_TRACKING_PREVENTION_LEVEL_BALANCED,
	COREWEBVIEW2_TRACKING_PREVENTION_LEVEL_STRICT
}
