using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

namespace Microsoft.Web.WebView2.Core.Raw;

[CompilerGenerated]
[TypeIdentifier("26D34152-879F-4065-BEA2-3DAA2CFADFB8", "Microsoft.Web.WebView2.Core.Raw.COREWEBVIEW2_TEXT_DIRECTION_KIND")]
public enum COREWEBVIEW2_TEXT_DIRECTION_KIND
{
	COREWEBVIEW2_TEXT_DIRECTION_KIND_DEFAULT,
	COREWEBVIEW2_TEXT_DIRECTION_KIND_LEFT_TO_RIGHT,
	COREWEBVIEW2_TEXT_DIRECTION_KIND_RIGHT_TO_LEFT
}
