using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

namespace Microsoft.Web.WebView2.Core.Raw;

[CompilerGenerated]
[TypeIdentifier("26D34152-879F-4065-BEA2-3DAA2CFADFB8", "Microsoft.Web.WebView2.Core.Raw.COREWEBVIEW2_SERVER_CERTIFICATE_ERROR_ACTION")]
public enum COREWEBVIEW2_SERVER_CERTIFICATE_ERROR_ACTION
{
	COREWEBVIEW2_SERVER_CERTIFICATE_ERROR_ACTION_ALWAYS_ALLOW,
	COREWEBVIEW2_SERVER_CERTIFICATE_ERROR_ACTION_CANCEL,
	COREWEBVIEW2_SERVER_CERTIFICATE_ERROR_ACTION_DEFAULT
}
