using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

namespace Microsoft.Web.WebView2.Core.Raw;

[CompilerGenerated]
[TypeIdentifier("26D34152-879F-4065-BEA2-3DAA2CFADFB8", "Microsoft.Web.WebView2.Core.Raw.COREWEBVIEW2_PRINT_DUPLEX")]
public enum COREWEBVIEW2_PRINT_DUPLEX
{
	COREWEBVIEW2_PRINT_DUPLEX_DEFAULT,
	COREWEBVIEW2_PRINT_DUPLEX_ONE_SIDED,
	COREWEBVIEW2_PRINT_DUPLEX_TWO_SIDED_LONG_EDGE,
	COREWEBVIEW2_PRINT_DUPLEX_TWO_SIDED_SHORT_EDGE
}
