using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

namespace Microsoft.Web.WebView2.Core.Raw;

[CompilerGenerated]
[TypeIdentifier("26D34152-879F-4065-BEA2-3DAA2CFADFB8", "Microsoft.Web.WebView2.Core.Raw.COREWEBVIEW2_FILE_SYSTEM_HANDLE_PERMISSION")]
public enum COREWEBVIEW2_FILE_SYSTEM_HANDLE_PERMISSION
{
	COREWEBVIEW2_FILE_SYSTEM_HANDLE_PERMISSION_READ_ONLY,
	COREWEBVIEW2_FILE_SYSTEM_HANDLE_PERMISSION_READ_WRITE
}
