using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

namespace Microsoft.Web.WebView2.Core.Raw;

[CompilerGenerated]
[TypeIdentifier("26D34152-879F-4065-BEA2-3DAA2CFADFB8", "Microsoft.Web.WebView2.Core.Raw.COREWEBVIEW2_BROWSING_DATA_KINDS")]
public enum COREWEBVIEW2_BROWSING_DATA_KINDS
{
	COREWEBVIEW2_BROWSING_DATA_KINDS_FILE_SYSTEMS = 1,
	COREWEBVIEW2_BROWSING_DATA_KINDS_INDEXED_DB = 2,
	COREWEBVIEW2_BROWSING_DATA_KINDS_LOCAL_STORAGE = 4,
	COREWEBVIEW2_BROWSING_DATA_KINDS_WEB_SQL = 8,
	COREWEBVIEW2_BROWSING_DATA_KINDS_CACHE_STORAGE = 0x10,
	COREWEBVIEW2_BROWSING_DATA_KINDS_ALL_DOM_STORAGE = 0x20,
	COREWEBVIEW2_BROWSING_DATA_KINDS_COOKIES = 0x40,
	COREWEBVIEW2_BROWSING_DATA_KINDS_ALL_SITE = 0x80,
	COREWEBVIEW2_BROWSING_DATA_KINDS_DISK_CACHE = 0x100,
	COREWEBVIEW2_BROWSING_DATA_KINDS_DOWNLOAD_HISTORY = 0x200,
	COREWEBVIEW2_BROWSING_DATA_KINDS_GENERAL_AUTOFILL = 0x400,
	COREWEBVIEW2_BROWSING_DATA_KINDS_PASSWORD_AUTOSAVE = 0x800,
	COREWEBVIEW2_BROWSING_DATA_KINDS_BROWSING_HISTORY = 0x1000,
	COREWEBVIEW2_BROWSING_DATA_KINDS_SETTINGS = 0x2000,
	COREWEBVIEW2_BROWSING_DATA_KINDS_ALL_PROFILE = 0x4000,
	COREWEBVIEW2_BROWSING_DATA_KINDS_SERVICE_WORKERS = 0x8000
}
